### PR TITLE
docs(core): advanced optimization hints

### PR DESCRIPTION
**Pull request by yinonov**
self explanatory

### CODE REVIEW

**Comment by yinonov** [comment]
@tveinfeld will vvd-core get bundled in a stack once we migrate to single repo?

**Comment by tveinfeld** [comment]
> @tveinfeld will vvd-core get bundled in a stack once we migrate to single repo?

vvd-core will be translated into a simple shared library. most tree-shaking bundlers will leave this library outside the compilation if not needed.

**Comment by yinonov** [comment]
> > @tveinfeld will vvd-core get bundled in a stack once we migrate to single repo?
> 
> vvd-core will be translated into a simple shared library. most tree-shaking bundlers will leave this library outside the compilation if not needed.

see what this PR is about, I think in the core case, we might need to leave it as own module we can preload

**Comment by tveinfeld** [comment]
> > > @tveinfeld will vvd-core get bundled in a stack once we migrate to single repo?
> > 
> > 
> > vvd-core will be translated into a simple shared library. most tree-shaking bundlers will leave this library outside the compilation if not needed.
> 
> see what this PR is about, I think in the core case, we might need to leave it as own module we can preload

preloading fonts sounds reasonable (90K).. scheme files (comprised mainly of _incompressible long variable names_) are about ~7K each (usually only one loaded)..  In fact, the entire scheme doesn't add more than a _single component's_ css to the party.

**Comment by yinonov** [comment]
It's not about its weight but about its precedence. When scheme is discovered late, components may render without the expected styles

**Comment by tveinfeld** [comment]
> It's not about its weight but about its precedence. When scheme is discovered late, components may render without the expected styles

i'm for handing the end-user full control over how she loads/sets schemes. this can be achieved by embracing basic html building tools like <link> tags etc.

**Review by tveinfeld — APPROVED** [review]

**Comment by yinonov** [comment]
> > It's not about its weight but about its precedence. When scheme is discovered late, components may render without the expected styles
> 
> 
> 
> i'm for handing the end-user full control over how she loads/sets schemes. this can be achieved by embracing basic html tools like <link> tags etc.

Agree. Will be working on that separation. Closing

**Pull request closed without merging**
