### PR TITLE
fix(select): unneeded top padding

### PR DESCRIPTION
**Pull request by rachelbt**

### CODE REVIEW

**Review by yinonov — CHANGES_REQUESTED** [review]
setting label programmatically doesn't reflect on the attribute. which then causes a miss interpreted behavior;
by setting `document.querySelector('vwc-select').label = ''` will not change the label attribute

use `mdc-select--no-label` class which is set on shadowed container

**Comment by rachelbt** [comment]
> mdc-select--no-label

I saw that solution in textarea. Anyway using the class is way better! 
Changes as you suggested

**Review by yinonov — COMMENTED** [review]
seems stable now. wanna add to UI tests as well?

**Comment by rachelbt** [comment]
> seems stable now. wanna add to UI tests as well?

I've added ui-tests in this branch:
https://github.com/Vonage/vivid/pull/1133
Maybe we can merge the fix and I'll add the test there to prevent conflicts?

**Review by yinonov — APPROVED** [review]

**Pull request merged**
